# Generated by Django 4.1.7 on 2023-08-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0027_auto_20230822_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_invoice',
            name='cadrs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='cemail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
