# Generated by Django 4.1.7 on 2023-08-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0028_recurring_invoice_cadrs_recurring_invoice_cemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
