# Generated by Django 4.1.7 on 2023-08-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0029_customer_fname_customer_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Fname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Lname',
        ),
    ]
